apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eou81oazj-python
  janus-idp.io/tekton: eou81oazj-python
  backstage.io/kubernetes-id: eou81oazj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eou81oazj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
